SCR_MissionHeader {
 World "{74ED98C4568098A7}Worlds/Random/rTvT_Random_Cain/rTvT_RandomMission_CainSkirmish.ent"
 m_sName "Встречка Колгуев"
 m_sAuthor "Gubastus"
 m_sDetails "Podval event"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "rTvT"
 m_iPlayerCount 128
}