SCR_MissionHeader {
 World "{63401A999EA5CEE9}Worlds/Random/rTvT_Random_AlHadra_Base/TvT_Random_AlHadraCQB.ent"
 m_sName "CQB в Альхадре"
 m_sAuthor "Gubastus"
 m_sDetails "Podval event"
 m_sIcon "{B2B6376F5916FCF2}Assets/alhadra.edds"
 m_sLoadingScreen "{B2B6376F5916FCF2}Assets/alhadra.edds"
 m_sPreviewImage "{B2B6376F5916FCF2}Assets/alhadra.edds"
 m_sGameMode "rTvT"
 m_iPlayerCount 128
}