SCR_MissionHeader {
 World "{038ACB38319FF852}Worlds/Random/rTvT_RandomMission_Arland/TvT_RandomSkirmishMission_Arlandvanllaq.ent"
 m_sName "Битва за Арланд (Встречный)"
 m_sAuthor "Gubastus"
 m_sDetails "Podval event"
 m_sIcon "{94BD54887EAB8288}UI/Textures/MissionLoadingScreens/GM_Arland.edds"
 m_sLoadingScreen "{94BD54887EAB8288}UI/Textures/MissionLoadingScreens/GM_Arland.edds"
 m_sPreviewImage "{94BD54887EAB8288}UI/Textures/MissionLoadingScreens/GM_Arland.edds"
 m_sGameMode "rTvT"
 m_iPlayerCount 128
}