SCR_MissionHeader {
 World "{277B982295EC1195}Worlds/Random/rTvT_Ranodm_Zargabad/rTvT_Random_ZargabadBase.ent"
 m_sName "Рандом на Заргабаде"
 m_sAuthor "Gubastus"
 m_sDetails "Podval event"
 m_sIcon "{695DA5A2D0530C74}Assets/zargabad_preview_1.edds"
 m_sLoadingScreen "{695DA5A2D0530C74}Assets/zargabad_preview_1.edds"
 m_sPreviewImage "{695DA5A2D0530C74}Assets/zargabad_preview_1.edds"
 m_sGameMode "rTvT"
 m_iPlayerCount 128
}