SCR_MissionHeader {
 World "{41FAE6A1E3F11D8A}Worlds/Random/rTvT_Random_Zarichne/rTvT_RandomMission_ZarichneSkirmish.ent"
 m_sName "Бой в Заречном"
 m_sAuthor "RamboKZ"
 m_sDetails "Podval event"
 m_sIcon "{8D5429EA4F0DC490}Assets/zaricne.edds"
 m_sLoadingScreen "{8D5429EA4F0DC490}Assets/zaricne.edds"
 m_sPreviewImage "{8D5429EA4F0DC490}Assets/zaricne.edds"
 m_sGameMode "rTvT"
 m_iPlayerCount 128
}