SCR_MissionHeader {
 World "{E07B261E06E4EAC5}Worlds/Random/rTvT_RandomMission_Arland/TvT_RandomMission_Arlandvanilla.ent"
 m_sName "Битва за Арланд Ваниль"
 m_sAuthor "Gubastus"
 m_sDetails "Podval event"
 m_sIcon "{94BD54887EAB8288}UI/Textures/MissionLoadingScreens/GM_Arland.edds"
 m_sLoadingScreen "{94BD54887EAB8288}UI/Textures/MissionLoadingScreens/GM_Arland.edds"
 m_sPreviewImage "{94BD54887EAB8288}UI/Textures/MissionLoadingScreens/GM_Arland.edds"
 m_sGameMode "rTvT"
 m_iPlayerCount 128
 m_bRandomStartingWeather 1
}