SCR_MissionHeader {
 World "{74ED98C4568098A7}Worlds/Random/rTvT_Random_Cain/rTvT_RandomMission_CainSkirmish.ent"
 m_sName "Встречка Колгуев"
 m_sAuthor "Gubastus"
 m_sDetails "Podval event"
 m_sIcon "{269BD5A5DF17B042}UI/Textures/MissionLoadingScreens/Reforger_HQCArt_Kolguyev_UI.edds"
 m_sLoadingScreen "{14D609B3D45CCBED}UI/Textures/MissionLoadingScreens/CO_Cain.edds"
 m_sPreviewImage "{9067AC7C437EA0E2}UI/Textures/MissionLoadingScreens/GM_Cain_Horizontal.edds"
 m_sGameMode "rTvT"
 m_iPlayerCount 128
}