SCR_MissionHeader {
 World "{D67DBED0E2279602}Worlds/Random/rTvT_Random_Eden/rTvT_RandomMission_EdenVanilla.ent"
 m_sName "Рандом на Эвероне"
 m_sAuthor "Gubastus"
 m_sDetails "Podval event"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "rTvT"
 m_iPlayerCount 128
}