SCR_MissionHeader {
 World "{5D0C6D89A5B1396A}Worlds/Random/rTvT_RandomMission_Arland/TvT_RandomSkirmishMission_Arland.ent"
 m_sName "Битва за Арланд (Встречный)"
 m_sAuthor "Gubastus"
 m_sDetails "Podval event"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "rTvT"
 m_iPlayerCount 128
}