SCR_MissionHeader {
 World "{6A30DBE64B8293BA}Worlds/Random/rTvT_Random_AlHadra_Base/TvT_Random_AlHadraSkirmish.ent"
 m_sName "Встречный бой Альхадра"
 m_sAuthor "Gubastus"
 m_sDetails "Podval event"
 m_sIcon "{B2B6376F5916FCF2}Assets/alhadra.edds"
 m_sLoadingScreen "{B2B6376F5916FCF2}Assets/alhadra.edds"
 m_sPreviewImage "{B2B6376F5916FCF2}Assets/alhadra.edds"
 m_sGameMode "rTvT"
 m_iPlayerCount 128
}