SCR_MissionHeader {
 World "{6948D2AAFEF1C4DE}Worlds/Random/rTvT_RandomMission_Arland/TvT_RandomMission_ArlandBase.ent"
 m_sName "Битва за Арланд"
 m_sAuthor "Gubastus"
 m_sDetails "Podval event"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "rTvT"
 m_iPlayerCount 128
}