SCR_MissionHeader {
 World "{25DB1EB84E8553AC}Worlds/Random/rTvT_Random_Zarichne/rTvT_RandomMission_ZarichneBase.ent"
 m_sName "Битва за Заречное"
 m_sAuthor "RamboKZ"
 m_sDetails "Podval event"
 m_sIcon "{8D5429EA4F0DC490}Assets/zaricne.edds"
 m_sLoadingScreen "{8D5429EA4F0DC490}Assets/zaricne.edds"
 m_sPreviewImage "{8D5429EA4F0DC490}Assets/zaricne.edds"
 m_sGameMode "rTvT"
 m_iPlayerCount 128
}