SCR_MissionHeader {
 World "{7B53B5DFB669C99F}Worlds/Random/rTvT_Random_Eden/rTvT_RandomMission_EdenBase.ent"
 m_sName "Битва за Эверон"
 m_sAuthor "Gubastus"
 m_sDetails "Podval event"
 m_sIcon "{93E6EEDBCD12CA2F}UI/Textures/MissionLoadingScreens/GM_Eden.edds"
 m_sLoadingScreen "{93E6EEDBCD12CA2F}UI/Textures/MissionLoadingScreens/GM_Eden.edds"
 m_sPreviewImage "{93E6EEDBCD12CA2F}UI/Textures/MissionLoadingScreens/GM_Eden.edds"
 m_sGameMode "rTvT"
 m_iPlayerCount 128
}