SCR_MissionHeader {
 World "{038ACB38319FF852}Worlds/Random/rTvT_RandomMission_Arland/TvT_RandomSkirmishMission_Arlandvanllaq.ent"
 m_sName "Битва за Арланд (Встречный)"
 m_sAuthor "Gubastus"
 m_sDetails "Podval event"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "rTvT"
 m_iPlayerCount 128
}