SCR_MissionHeader {
 World "{724B209FC62666E3}Worlds/Random/rTvT_Random_Novka/TvT_Random_NovkaBase.ent"
 m_sName "Рандом на Новке"
 m_sAuthor "Gubastus"
 m_sDetails "Podval event"
 m_sIcon "{EE16A5F0FA750DEB}Assets/novka.edds"
 m_sLoadingScreen "{EE16A5F0FA750DEB}Assets/novka.edds"
 m_sPreviewImage "{EE16A5F0FA750DEB}Assets/novka.edds"
 m_sGameMode "rTvT"
 m_iPlayerCount 128
}