SCR_MissionHeader {
 World "{F8548330448ACD84}Worlds/Random/rTvT_Random_Novka/TvT_Random_NovkaSkirmish.ent"
 m_sName "Встречный бой на Новке"
 m_sAuthor "Gubastus"
 m_sDetails "Podval event"
 m_sIcon "{EE16A5F0FA750DEB}Assets/novka.edds"
 m_sLoadingScreen "{EE16A5F0FA750DEB}Assets/novka.edds"
 m_sPreviewImage "{EE16A5F0FA750DEB}Assets/novka.edds"
 m_sGameMode "rTvT"
 m_iPlayerCount 128
}