SCR_MissionHeader {
 World "{4BCA4BCF10D6A96F}Worlds/Random/rTvT_Random_Bellau/rTvT_Random_BellauBase.ent"
 m_sName "Битва за Беллау"
 m_sAuthor "Gubastus"
 m_sDetails "Podval event"
 m_sIcon "{11886DB716267A7D}Assets/belleau.edds"
 m_sLoadingScreen "{11886DB716267A7D}Assets/belleau.edds"
 m_sPreviewImage "{11886DB716267A7D}Assets/belleau.edds"
 m_sGameMode "rTvT"
 m_iPlayerCount 128
}