SCR_MissionHeader {
 World "{326144E4C0E77B26}Worlds/Random/rTvT_Random_Eden/rTvT_RandomMission_EdenSkirmish.ent"
 m_sName "Встречка Эверон"
 m_sAuthor "Gubastus"
 m_sDetails "Podval event"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "rTvT"
 m_iPlayerCount 128
}