SCR_MissionHeader {
 World "{B37D801C1D4024CA}Worlds/Random/rTvT_Random_Eden/rTvT_RandomMission_EdenSkirmishvani.ent"
 m_sName "Встречка Эверон"
 m_sAuthor "Gubastus"
 m_sDetails "Podval event"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "rTvT"
 m_iPlayerCount 128
}