SCR_MissionHeader {
 World "{4AFE7EBF66E46C4A}Worlds/Random/rTvT_Random_Cain/rTvT_RandomMission_CainSkirmishvamilla.ent"
 m_sName "Встречка Колгуев"
 m_sAuthor "Gubastus"
 m_sDetails "Podval event"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "rTvT"
 m_iPlayerCount 128
}