SCR_MissionHeader {
 World "{53C60B6EAC6B6B4F}Worlds/Random/rTvT_Random_Cain/rTvT_RandomMission_CainVanilla.ent"
 m_sName "Битва за Колгуев"
 m_sAuthor "Gubastus"
 m_sDetails "Podval event"
 m_sIcon "{269BD5A5DF17B042}UI/Textures/MissionLoadingScreens/Reforger_HQCArt_Kolguyev_UI.edds"
 m_sLoadingScreen "{14D609B3D45CCBED}UI/Textures/MissionLoadingScreens/CO_Cain.edds"
 m_sPreviewImage "{9067AC7C437EA0E2}UI/Textures/MissionLoadingScreens/GM_Cain_Horizontal.edds"
 m_sGameMode "rTvT"
 m_iPlayerCount 128
}