SCR_MissionHeader {
 World "{53C60B6EAC6B6B4F}Worlds/Random/rTvT_Random_Cain/rTvT_RandomMission_CainVanilla.ent"
 m_sName "Битва за Колгуев"
 m_sAuthor "Gubastus"
 m_sDetails "Podval event"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "rTvT"
 m_iPlayerCount 128
}