SCR_MissionHeader {
 World "{9CB04D355E56A806}Worlds/Random/rTvT_Random_Anizay/TvT_Random_AnizayBase.ent"
 m_sName "Рандом на Анизае"
 m_sAuthor "Gubastus"
 m_sDetails "Podval event"
 m_sIcon "{6CFADAEE9287D1D2}UI/Textures/MissionThumbnails/Default.edds"
 m_sGameMode "rTvT"
 m_iPlayerCount 128
}