SCR_MissionHeader {
 World "{9CB04D355E56A806}Worlds/Random/rTvT_Random_Anizay/TvT_Random_AnizayBase.ent"
 m_sName "Рандом на Анизае"
 m_sAuthor "Gubastus"
 m_sDetails "Podval event"
 m_sIcon "{6B0C5B8DAA869F09}Assets/anizay.edds"
 m_sLoadingScreen "{6B0C5B8DAA869F09}Assets/anizay.edds"
 m_sPreviewImage "{6B0C5B8DAA869F09}Assets/anizay.edds"
 m_sGameMode "rTvT"
 m_iPlayerCount 128
}